[build-system]
requires = ["setuptools>=68", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "pack_name"
version = "0.1.0"
description = "My package"
requires-python = ">=3.9"

[tool.setuptools]
package-dir = {"" = "simpleoring"}